language: java
jdk:
- openjdk7
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database newsletter;' -U postgres
script: export DATABASE_URL=postgres://postgres@localhost/newsletter &&
  mvn test
deploy:
  app: eurisko-newsletter-api
  provider: heroku
  api_key:
    secure: S7hT7Ugg7v3e1GTJb2jCn0MsHb8+0JB2gHv9In5CK0uonA0mLnAOfgnmNQw0/um0lIXkBjdExUaxvLfkPsY+CSmPhWIJQ0hQ6pNkDdLCB/s/sBkisZag3wpZOq/1x9ddFYQQyzE37bKAh6MMR+KeiKTNFFBjlJKPEBJHZrlwJV4=
