language: java
jdk:
  - openjdk7
  - oraclejdk7
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database newsletter;' -U postgres
script: "export DATABASE_URL=jdbc:postgresql://localhost/newsletter?user=postgres && mvn test"
